[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "multitask_RL"
version = "0.1.0"
description = "Repository for multitask_RL implementations and experiments"
readme = "README.md"
requires-python = ">=3.11"
license = { file = "LICENSE" }
dependencies = [
    "torch",
    "tensorflow",
    "tensorflow-datasets",
    "tensorflow-probability[tf]",
    "tensorflow-hub",
    "tensorflow-text",
    "dlimp",
    "jax[cuda12]",
    "flax",
    "distrax",
    "ml_collections",
    "matplotlib",
    "moviepy",
    "wandb",
    "jupyter",
    "ipykernel",
    "ipywidgets",
    "rich"
]

[project.urls]
Repository = "https://github.com/yajatyadav/multitask_RL"

[tool.uv.sources]
dlimp = { git = "https://github.com/yajatyadav/dlimp", branch = "main" }

[tool.setuptools.packages.find]
where = ["."]
exclude = ["cache"]